apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartgrid-ms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smartgrid-ms
    spec:
      containers:
      - name: smartgrid-ms
        image: 10.0.2.62:5000/gridvo/smartgrid-ms:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
             
