apiVersion: v1
kind: Service
metadata:
  labels:
    name: smartgrid-ms
  name: smartgrid-ms
  namespace: gridvo
spec:
  selector:
    name: smartgrid-ms
  type: NodePort
  ports:
     - port: 80
       targetPort: 3001
       nodePort: 31012
